# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Nenets spellchecker"
yrk = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Nenets, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
yrk = "TRANSLATE: A spellchecker for Nenets, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.yrk"

[windows]
system_product_code = "{1459D8BF-A7F8-4499-AFE9-D25CBD7AE69B}_is1"
legacy_product_codes = [
    { value = "1357CEA4-CD3F-4872-B9EE-902C9E307E85", kind = "nsis" },
    { value = "EEC0E9D0-876A-45F3-A640-53CB4E8CFDBA", kind = "nsis" }
]

[package.speller]
name = "Nenets"
version = "0.1.1"

[package.grammar]
name = "Nenets"
version = "0.1.0"

[package.tts-text-proc]
name = "Nenets"
version = "0.1.0"

[package.hyphenator]
name = "__UNDEFINED__"
version = "0.1.0"
