template = "https://github.com/giellalt/template-lang-und"
rev_id = 93
template_sha = "76239a3aabbd1c3f9424021323d9979df3bff322"

[replacements]
__REPO__ = "lang-yrk"
__UND2C__ = "yrk"
__UNDEFINED__ = "Nenets"
__UND__ = "yrk"
