template = "https://github.com/giellalt/template-lang-und"
rev_id = 262
template_sha = "e76bfc45ca43118d648ca429564512658ac2ea78"

[replacements]
__GLOTTOLOG_ID__ = "nene1249"
__REPO__ = "lang-yrk"
__UND2C__ = "yrk"
__UNDEFINED__ = "Nenets"
__UND__ = "yrk"
